### PR TITLE
Removed dependency on node-gyp

### PR DESCRIPTION
**Pull request by piranna**
Use the one bundled with npm. Also, npm itself compiles it on install when if finds a bindings.gyp file

### CODE REVIEW

**Comment by jprichardson** [comment]
Ref: https://github.com/jprichardson/node-kexec/issues/23

**Comment by piranna** [comment]
Thanks for the reference to the issue, I forgot it :-)

**Comment by foysavas** [comment]
Looks good to me.

**Comment by btakita** [comment]
Would this fix the install issue of kexec on node 4.2.2?

**Comment by piranna** [comment]
Any update on this?

**Comment by btakita** [comment]
+1 This would allow me to upgrade my project to node 4.2.2.

**Comment by foysavas** [comment]
Just merged this into master. @jprichardson can you publish to npm?

**Comment by jprichardson** [comment]
Oops, sorry... doing this now.

**Comment by jprichardson** [comment]
Done.

**Comment by piranna** [comment]
Thank you :-)

**Pull request merged**
